.phony: force
all: force
	$(make) -c .. dzcoin_qt test_dzcoin_qt
clean: force
	$(make) -c .. dzcoin_qt_clean test_dzcoin_qt_clean
check: force
	$(make) -c .. test_dzcoin_qt_check
dzcoin-qt dzcoin-qt.exe: force
	 $(make) -c .. dzcoin_qt


